
obj-y				+= adux1050/
obj-y				+= bu520x1nvx/
obj-y				+= camera_sync/
obj-y				+= et6xx/
obj-y				+= flash_led/
obj-y				+= hdmi_detect/
obj-y				+= ldo_vibrator/
obj-y				+= pn553/
obj-y				+= powerkey_forcecrash/
obj-y				+= sec_ts/
obj-y				+= slg51000_regulator/
obj-y				+= sony_camera/
obj-y				+= tcs3490/
header-y			+= include/
